mebn/DD2480

assignment1_DECIDE/src/LaunchInterceptor.java

add: lic 5

---

assignment1_DECIDE/src/LaunchInterceptor.java

Issue/24 closes #24

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestLIC_7.java

add: lic 7

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestLIC_4.java

add: lic 4

---

assignment1_DECIDE/src/LaunchInterceptor.java

First version of LIC2. Only one test currently passes but I believe the tests aren't fully working (look at issue #46). This pull request refers to issue #23. Will close #23 once we have passing tests

Add: LIC2 (Issue/23)

---

assignment1_DECIDE/src/tests/TestLIC_2.java

Wrote new tests for LIC requirements. Added comments explaining the logic behind test cases. Let me know if its unclear at all
closes #46

Fixed Tests for LIC2 Issue/46

---

assignment1_DECIDE/src/LaunchInterceptor.java

Added the functionality for LIC11. All tests are passing. Closes #32

Add: LIC11 (#32)

---

assignment1_DECIDE/src/tests/TestLIC_10.java
assignment1_DECIDE/src/tests/TestLIC_2.java

Add: Unittests for LIC 10 Issue/15

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestLIC_8.java

Added unittests for LIC8,
Changed all checkLIC's to public for testing
Closes #13

Add: Unittests for LIC8

---

assignment1_DECIDE/src/Point.java

Added a class to represent a point in cartesian coordinates. Implements some functionality I feel is missing from the currently used classes. If this pull request is approved I will create and issue to refactor existing code to use this class instead.
Closes (#37)

Add: issue #37 Adds a point class

---

assignment1_DECIDE/src/LaunchInterceptor.java

LIC8 implementation is very similar to LIC1 #48, so we might want to have some general methods we can call. Someone talked about that but I don't know where/who.
closes #29

Add: issue #29 add implementation for LIC8

---

README.md
assignment1_DECIDE/README.md

Added some information on how to name stuff. Also, how to run DECIDE program and tests.
Closes #59.

Doc: issue #59 add documentation to README files

---

assignment1_DECIDE/src/GeometryUtils.java
assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestLIC_9.java

Adds implementation for LIC9 as well as two more test cases. It passes all tests. 
Also adds the GeometryUtils class to do parts of the calculations of LIC9.
Closes #30

Add: issue #30 Implementation for LIC9 and GeometryUtils class

---

assignment1_DECIDE/src/LaunchInterceptor.java

Added the functionality for LIC_6.
All tests are passing.
Closes #27

Add: issue #27 Added the functionality for LIC_6

---

assignment1_DECIDE/src/tests/TestLIC_13.java

Adds unittests for LIC_13
closes #18

Add: issue #18 Adds unittest for LIC_13

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestLIC_6.java

There was a bug in LIC_6. This fixes that bug and adds a testcase to catch that specific instance.
closes #69

Fix: issue #69 Fixed a bug in LIC_6 and added test case.

---

assignment1_DECIDE/src/LaunchInterceptor.java

No test for this one.
closes #77

Add: issue #77 method for calculating CMV

---

assignment1_DECIDE/src/LaunchInterceptor.java

Adds skeleton code for calculating, getting, and setting CMV, PUM, and FUV.
I did this mainly so I could continue working on test-creation. If anyone has a better sugestion for how they want to structure the code, feel free to do so!
closes #80

Add: issue #80 Add skeleton for remaining functions

---

assignment1_DECIDE/src/GeometryUtils.java
assignment1_DECIDE/src/LaunchInterceptor.java

Refactors LIC1, LIC2, LIC3 and LIC8 to use GeometryUtils
There are more check_LIC's to refactor such as 6 and 12 but didn't have time to do that right now. 
Partially solves Issue #74 and #73

Refactor: issue #74,#73 check_LIC's now use GeometryUtils

---

assignment1_DECIDE/src/LaunchInterceptor.java

Add: Issue #31 Implement LIC10 functionality with GeometryUtils

---

assignment1_DECIDE/src/LaunchInterceptor.java

Add: Issue #35 Add Implementation of LIC14 functionality

---

assignment1_DECIDE/src/LaunchInterceptor.java

Adds the code for checkLIC_12
Passes all tests.
Closes #33

Add: issue #33 Added functionality for LIC_12

---

assignment1_DECIDE/src/tests/TestLIC_12.java

Fix: Issue #90 Fixed boundary conditions for LIC12 test case

---

assignment1_DECIDE/src/LaunchInterceptor.java

Adds the functionality needed to calculate the PUM
closes #65

Add: issue #65 Add function to calculate PUM

---

assignment1_DECIDE/src/LaunchInterceptor.java

No tests for this one
FUV[i] = true (if PUV[i] == false OR if all PUM[i][j] == true)
closes #67

Add: issue #67 calculate FUV

---

assignment1_DECIDE/src/LaunchInterceptor.java

Implements the logic for decide to return a boolean true signal if all elements of FUV are true. Otherwise returns false.
Closes #95

Add: issue #95 Implemented DECIDE function

---

CONTRIBUTING.md
README.md
assignment1_DECIDE/README.md

Doc: add a `CONTRIBUTING.md` file and update docs

---

assignment1_DECIDE/src/tests/TestLIC_10.java

Fix: Issue #91 Change testcases to check for thrown exception

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/Operator.java
assignment1_DECIDE/src/tests/TestDecide.java

Add three successful tests to decide. 
We still need to update these further and also add unsuccessful tests, but it's a decent first version.
Addresses #72

Add: issue #72 tests for decide 

---

assignment1_DECIDE/src/GeometryUtils.java
assignment1_DECIDE/src/LaunchInterceptor.java
assignment1_DECIDE/src/tests/TestDecide.java
assignment1_DECIDE/src/tests/TestLIC_0.java
assignment1_DECIDE/src/tests/TestLIC_1.java
assignment1_DECIDE/src/tests/TestLIC_10.java
assignment1_DECIDE/src/tests/TestLIC_11.java
assignment1_DECIDE/src/tests/TestLIC_12.java
assignment1_DECIDE/src/tests/TestLIC_13.java
assignment1_DECIDE/src/tests/TestLIC_14.java
assignment1_DECIDE/src/tests/TestLIC_2.java
assignment1_DECIDE/src/tests/TestLIC_3.java
assignment1_DECIDE/src/tests/TestLIC_4.java
assignment1_DECIDE/src/tests/TestLIC_5.java
assignment1_DECIDE/src/tests/TestLIC_6.java
assignment1_DECIDE/src/tests/TestLIC_7.java
assignment1_DECIDE/src/tests/TestLIC_8.java
assignment1_DECIDE/src/tests/TestLIC_9.java

Adds test documentation
Refactors to remove unused and duplicate imports.
Closes #100

Doc: issue #100 Adds comments describing all test cases in natural language

---

README.md
assignment1_DECIDE/README.md

Added my statement of contributions.
Relates to #104

Doc: issue #104 Added statement of contributions for all group members

---

.github/workflows/assignment2.yml

added a github action for assignment 2 that will run `cargo build` and `cargo test` on pull requests into main and every commit in main.

Add: github action for assignment 2 and rust

---

.gitignore
assignment2/Cargo.lock
assignment2/Cargo.toml
assignment2/src/main.rs
assignment2/src/routes/frontend.rs

Fix: issue #136 fixed unit tests, removed async

---

.gitignore
assignment2/src/routes/frontend.rs
assignment2/tests/logs_frontend/commit-1/build.log
assignment2/tests/logs_frontend/commit-1/test.log
assignment2/tests/logs_frontend/commit-2/build.log
assignment2/tests/logs_frontend/commit-2/test.log

Removed all IO operations from fronend tests. Write to file, create/delete files/folders somtimes work, sometimes don't. Hopefully this fixes it for good
closes #138

Fix: issue #138 removed io operations for frontend unit tests

---

assignment1_DECIDE/src/LaunchInterceptor.java
assignment2/README.md

Added the necessary parts to the readme file.
Please fill out your statement of contributions before merging.
Eventually closes #131

Doc: Issue #131 completes the readme file
